version: 2
updates:
  - package-ecosystem: 'github-actions'
    directories:
      - '/'
    schedule:
      interval: 'monthly'
      day: 'sunday'
    open-pull-requests-limit: 10

  - package-ecosystem: 'npm'
    directories:
      - '/'
    schedule:
      interval: 'monthly'
      day: 'sunday'
    groups:
      dependencies:
        update-types:
          - 'minor'
          - 'patch'
    open-pull-requests-limit: 10
