name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Github - Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: PNPM - Setup
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: 10

      - name: Node.js - Setup
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: PNPM - Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Changesets - Create release pull request or publish to npm
        uses: changesets/action@v1
        with:
          commit: 'chore: release eslint-config-kylsgl'
          commitMode: 'github-api'
          publish: pnpm release
          title: 'chore: release eslint-config-kylsgl'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }} # Use PAT to trigger workflow events
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
